### ISSUE TITLE
Processing of classification attributes

### ISSUE THREAD

**Issue by liu888666** [vinspdb/MiDA#2]
Why does the classification attribute in the paper require one-hot encoding before embedding, but only the label value is encoded with one-hot encoding in the code？

**Comment by vinspdb** [comment]
Example:

Sentences:
1) The pen is on the table
2) The pen is red

Index based conversion:
1) [0, 1, 2, 3, 4, 5]
2) [0, 1, 2, 6]

For an intuition of how this table lookup is implemented as a mathematical operation which can be handled by the automatic differentiation engines, consider the embeddings table from the example as a (7, 2) matrix. 
+------------+------------+
|   index    |  Embedding |
+------------+------------+
|     0      | [1.2, 3.1] |
|     1      | [0.1, 4.2] |
|     2      | [1.0, 3.1] |
|     3      | [0.3, 2.1] |
|     4      | [2.2, 1.4] |
|     5      | [0.7, 1.7] |
|     6      | [4.1, 2.0] |
+------------+------------+
Then, for a given word, the embedding keras layer create a one-hot vector based on its index and multiply it by the embeddings matrix, effectively replicating a lookup. 
For instance, for the word "soon" the index is 4, and the one-hot vector is [0, 0, 0, 0, 1, 0, 0]. If you multiply this (1, 7) matrix by the (7, 2) embeddings matrix you get the desired two-dimensional embedding, which in this case is [2.2, 1.4].
